### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by oyayasuhisa** [oyayasuhisa/chat-space#17]
# IPアドレス
3.113.54.41

**Comment by yasunamiura** [comment]
大宅さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
- 非同期・自動更新のときにメッセージにCSSが当たるようにしましょう
[![Image from Gyazo](https://i.gyazo.com/1dab5ad1f47658c22d4d7064cdd08c3f.png)](https://gyazo.com/1dab5ad1f47658c22d4d7064cdd08c3f)
見本
[![Image from Gyazo](https://i.gyazo.com/8bff179347005f995a55ee7806e29f5d.png)](https://gyazo.com/8bff179347005f995a55ee7806e29f5d)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
